### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Maurice-Betzel** [cschneider/osgi-best-practices#3]
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /C:/Dev/osgi-best-practices/backend/src/main/java/net/lr/tasklist/model/Task.java:[5,33] package javax.xml.bind.annotation does not exist
[ERROR] /C:/Dev/osgi-best-practices/backend/src/main/java/net/lr/tasklist/model/Task.java:[7,2] cannot find symbol
  symbol: class XmlRootElement

**Comment by cschneider** [comment]
Which java version do you use?

**Comment by Maurice-Betzel** [comment]
Still using Java 8 on path and in project settings:
java -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_202-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.202-b08, mixed mode)

Experimenting with Java 11 and it is know that the java.xml.bind package is removed.

**Comment by Maurice-Betzel** [comment]
Correction, taking a look at my maven install:

C:\Program Files\AdoptOpenJDK\jdk-11.0.5.10-openj9\bin\java.exe" 

WTF?

**Comment by Maurice-Betzel** [comment]
Intellij is running Java 8, all setting say Java 8, what is happening here?

IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Licensed to Maurice Betzel
You have a perpetual fallback license for this version
Subscription is active until January 1, 2022
Runtime version: 1.8.0_212-release-1586-b12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1965M
Cores: 8
Registry: 
Non-Bundled Plugins: MetricsReloaded, Statistic, com.dmarcotte.handlebars, com.vaadin.designer2.intellij, de.netnexus.camelcaseplugin, net.seesharpsoft.intellij.plugins.csv, org.apache.camel, org.asciidoctor.intellij.asciidoc

**Comment by Maurice-Betzel** [comment]
If i use a custom maven run configuration with Java 8 all is OK. Strange thing is that Intellij reports Java 8 in project, maven and runtime settings.

**Comment by Maurice-Betzel** [comment]
Jump to conclusions too fast, next issue:

INFO: Waiting for remote bundle context.. on 21001 name: 524a832e-3cd8-4db5-b5bf-73e26242ba73 timout: [ RelativeTimeout value = 180000 ]
org.apache.felix.resolver.reason.ReasonException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=test-dependencies; type=karaf.feature; version="[0,0.0.0]"; filter:="(&(osgi.identity=test-dependencies)(type=karaf.feature)(version>=0.0.0)(version<=0.0.0))" [caused by: Unable to resolve test-dependencies/0.0.0: missing requirement [test-dependencies/0.0.0] osgi.identity; osgi.identity=net.lr.osgibp.backend; type=osgi.bundle; version="[1.0.0.202001241509,1.0.0.202001241509]"; resolution:=mandatory [caused by: Unable to resolve net.lr.osgibp.backend/1.0.0.202001241509: missing requirement [net.lr.osgibp.backend/1.0.0.202001241509] osgi.wiring.package; filter:="(osgi.wiring.package=javax.ws.rs)"]]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:392)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:378)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:332)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:257)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:393)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1062)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$13(FeaturesServiceImpl.java:998)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve test-dependencies/0.0.0: missing requirement [test-dependencies/0.0.0] osgi.identity; osgi.identity=net.lr.osgibp.backend; type=osgi.bundle; version="[1.0.0.202001241509,1.0.0.202001241509]"; resolution:=mandatory [caused by: Unable to resolve net.lr.osgibp.backend/1.0.0.202001241509: missing requirement [net.lr.osgibp.backend/1.0.0.202001241509] osgi.wiring.package; filter:="(osgi.wiring.package=javax.ws.rs)"]
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 12 more
Caused by: org.apache.felix.resolver.reason.ReasonException: Unable to resolve net.lr.osgibp.backend/1.0.0.202001241509: missing requirement [net.lr.osgibp.backend/1.0.0.202001241509] osgi.wiring.package; filter:="(osgi.wiring.package=javax.ws.rs)"
	at org.apache.felix.resolver.Candidates$MissingRequirementError.toException(Candidates.java:1343)
	... 13 more
